# Generated by Django 3.2.5 on 2021-07-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0003_remove_movie_available_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='open_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube',
            field=models.TextField(blank=True),
        ),
    ]
