# Generated by Django 3.2.5 on 2021-07-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0006_alter_movie_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
