# Generated by Django 3.2.5 on 2021-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AddField(
            model_name='movie',
            name='available_display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='movie',
            name='available_order',
            field=models.BooleanField(default=True, verbose_name='Order'),
        ),
    ]
