# Generated by Django 3.2.5 on 2021-07-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0002_auto_20210716_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='available_order',
        ),
    ]
