# Generated by Django 3.2.5 on 2021-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0004_auto_20210720_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
