# Generated by Django 3.2.5 on 2021-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0005_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
